### ISSUE TITLE
FeatureOrder not respected by GenericCommandManager

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug#357] opened 2021-07-05 17:06 UTC
**Describe the bug**
`manager.lock().await.update_vibration(&message, true)?;` for a device where the feature order has be redefined in the config gets feature 0 at index 0 when feature 0 is defined as having an index of 1.

**Expected behavior**
feature 0's value should be at index 1

**Actual behavior**
feature 0's value should be at index 0

**Comment by qdot** [comment] 2022-02-06 01:59
Just found the cause for this! We were never actually loading the feature order. I had accidentally used #[serde(skip)] instead of #[serde(skip_serialization)], which means we skipped both serialization AND deserialization. This should be fixed in Buttplug v6, and it's an easy fix to backport into the v5 tree if need be.

**Comment by qdot** [comment] 2022-08-02 07:01
Feature order removed in v6, will close on landing.

**Closed** 2022-08-28 23:57 UTC
Labels: bug
